version: '3.8'

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:

services:
  giver:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command:
      - bash
      - -c
      - |
        uvicorn --host=0.0.0.0 --app-dir=/usr/src/giver/ main:app --reload
    restart: on-failure
    env_file:
      - local/giver.env
      - local/postgres.env
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - ./:/usr/src/giver/
    depends_on:
      - postgres
      - redis
    networks:
      - network

  postgres:
    image: "postgres:14.3-alpine"
    env_file:
      - local/postgres.env
    ports:
      - target: 5432
        published: 5532
        protocol: tcp
        mode: host
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: "redis:7.0.0-alpine"
    volumes:
      - redis-data:/data
    networks:
      - network

