version: '3.8'

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:

services:
  phoenix:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command:
      - bash
      - -c
      - |
        alembic upgrade head
        uvicorn --host=0.0.0.0 --app-dir=/usr/src/phoenix/ main:app --reload
    restart: on-failure
    env_file:
      - local/phoenix.env
      - local/postgres.env
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - ./:/usr/src/phoenix/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - network

  postgres:
    image: "postgres:14.3-alpine"
    env_file:
      - local/postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - target: 5432
        published: 5532
        protocol: tcp
        mode: host
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: "redis:7.0.0-alpine"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - redis-data:/data
    networks:
      - network

